(function () {
  "use strict";
  globalThis.__fontPluginStage = "state";
  const shared = globalThis.FontPluginShared;
  if (!shared) {
    globalThis.__fontPluginStage = "state_no_shared";
    throw new Error("FontPluginShared not found. Is shared.js loaded?");
  }
  const state = {
    activeTab: "inspect",
    currentHostname: "",
    currentTabId: null,
    currentTabUrl: "",
    defaultTypography: { ...shared.DEFAULT_TYPOGRAPHY },
    draftSetting: shared.normalizeSiteSetting({}),
    favoriteFontIds: [],
    fonts: {},
    recentFontIds: [],
    selectedFontId: "",
    siteSettings: {},
    storageBytesUsed: 0,
    supportedPage: false,
    targetNotFoundHosts: {},
    theme: "system",
    showPageBadge: true,
    sitesSearchQuery: "",
    fontSearchQuery: "",
    sitesSortBy: "domain",
    globalOverride: { enabled: false, fontId: "" },
    copiedSiteSetting: null,
    previewPaused: false,
    siteRules: [],
    activeRuleIdx: 0
  };
  const elements = {
    applyButton: document.getElementById("applyButton"),
    deleteButton: document.getElementById("deleteButton"),
    favoriteButton: document.getElementById("favoriteButton"),
    fontFile: document.getElementById("fontFile"),
    fontSearch: document.getElementById("fontSearch"),
    fontSelect: document.getElementById("fontSelect"),
    fontSizeInput: document.getElementById("fontSizeInput"),
    fontWeightSelect: document.getElementById("fontWeightSelect"),
    letterSpacingInput: document.getElementById("letterSpacingInput"),
    lineHeightInput: document.getElementById("lineHeightInput"),
    overrideCheckbox: document.getElementById("overrideCheckbox"),
    ovrText: document.getElementById("ovrText"),
    siteDot: document.getElementById("siteDot"),
    panelApply: document.getElementById("panelApply"),
    panelSites: document.getElementById("panelSites"),
    panelUpload: document.getElementById("panelUpload"),
    panelInspect: document.getElementById("panelInspect"),
    pickerButton: document.getElementById("pickerButton"),
    repickTargetButton: document.getElementById("repickTargetButton"),
    resetButton: document.getElementById("resetButton"),
    saveAsDefaultButton: document.getElementById("saveAsDefaultButton"),
    selectorWarning: document.getElementById("selectorWarning"),
    siteLabel: document.getElementById("siteLabel"),
    sitesEmpty: document.getElementById("sitesEmpty"),
    sitesList: document.getElementById("sitesList"),
    statusMessage: document.getElementById("statusMessage"),
    tabApply: document.getElementById("tabApply"),
    tabSites: document.getElementById("tabSites"),
    tabUpload: document.getElementById("tabUpload"),
    tabInspect: document.getElementById("tabInspect"),
    targetModeSelect: document.getElementById("targetModeSelect"),
    targetNotFoundBanner: document.getElementById("targetNotFoundBanner"),
    targetSummary: document.getElementById("targetSummary"),
    textOnlyCheckbox: document.getElementById("textOnlyCheckbox"),
    relaxLayoutCheckbox: document.getElementById("relaxLayoutCheckbox"),
    themeSelect: document.getElementById("themeSelect"),
    uploadButton: document.getElementById("uploadButton"),
    useWholePageButton: document.getElementById("useWholePageButton"),
    storageUsage: document.getElementById("storageUsage"),
    hotkeyHint: document.getElementById("hotkeyHint"),
    showPageBadgeCheckbox: document.getElementById("showPageBadgeCheckbox"),
    sitesSearch: document.getElementById("sitesSearch"),
    exportButton: document.getElementById("exportButton"),
    importFile: document.getElementById("importFile"),
    fontFeatureSettingsInput: document.getElementById("fontFeatureSettingsInput"),
    opentypeFeaturesWrap: document.getElementById("opentypeFeaturesWrap"),
    sitesSortBy: document.getElementById("sitesSortBy"),
    copyFromCurrentButton: document.getElementById("copyFromCurrentButton"),
    sitesCopyHint: document.getElementById("sitesCopyHint"),
    cleanupUnusedButton: document.getElementById("cleanupUnusedButton"),
    globalOverrideCheckbox: document.getElementById("globalOverrideCheckbox"),
    fontStyleSelect: document.getElementById("fontStyleSelect"),
    wordSpacingInput: document.getElementById("wordSpacingInput"),
    textTransformSelect: document.getElementById("textTransformSelect"),
    textColorInput: document.getElementById("textColorInput"),
    textDecorationSelect: document.getElementById("textDecorationSelect"),
    textShadowSelect: document.getElementById("textShadowSelect"),
    textOpacityInput: document.getElementById("textOpacityInput"),
    copyCssButton: document.getElementById("copyCssButton"),
    undoButton: document.getElementById("undoButton"),
    redoButton: document.getElementById("redoButton"),
    savePresetButton: document.getElementById("savePresetButton"),
    presetNameInput: document.getElementById("presetNameInput"),
    presetsGrid: document.getElementById("presetsGrid"),
    checkAccessibilityButton: document.getElementById("checkAccessibilityButton"),
    accessibilityStatus: document.getElementById("accessibilityStatus"),
    shortcutsHint: document.getElementById("shortcutsHint"),
    accPresets: document.getElementById("accPresets"),
    accFontPairs: document.getElementById("accFontPairs"),
    accAccessibility: document.getElementById("accAccessibility"),
    focusCaptureButton: document.getElementById("focusCaptureButton"),
    rulesChips: document.getElementById("rulesChips"),
    rulesEditingLabel: document.getElementById("rulesEditingLabel"),
    addRuleBtn: document.getElementById("addRuleBtn"),
    snapshotButton: document.getElementById("snapshotButton"),
    shareSiteButton: document.getElementById("shareSiteButton"),
    shareDialog: document.getElementById("shareDialog"),
    shareCode: document.getElementById("shareCode"),
    shareCloseBtn: document.getElementById("shareCloseBtn"),
    copyShareCodeBtn: document.getElementById("copyShareCodeBtn"),
    downloadShareBtn: document.getElementById("downloadShareBtn")
  };
  const STORAGE_WARN_BYTES = 8 * 1024 * 1024;
  globalThis.FontPluginPopup = {
    state,
    elements,
    STORAGE_WARN_BYTES,
    liveApplyTimer: null
  };
})();
